language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop
  - /^release-.*$/
  - travis-test

install:
  - pip install -r requirements.txt

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: iconfoundation
  server: https://test.pypi.org/legacy/
  password: $PYPI_PW
  on:
    branch: travis-test
