language: python
python:
  - "3.7"
dist: bionic
services:
- docker

matrix:
 allow_failures:
  - python: "3.6"


branches:
  only:
  - master
  - develop
  - /^release/.*$/
  - travis-test-test

install:
  - pip install -e .[tests]

script:
  - pytest -vv

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: iconfoundation
  password: $PYPI_PW
  on:
    branch: master
